version: 2.1

orbs:
    node: circleci/node@5.1.0

jobs:
    build-and-test:
        docker:
            - image: cimg/node:12.16
        parallelism: 5
        steps:
            - checkout
            - run:
                name: Stop execution if not running any tests 
                command: |
                    mkdir -p ./tmp && \
                    >./tmp/tests.txt && \
                    circleci tests glob "src/__tests__/*.js" | circleci tests run --command=">./tmp/tests.txt xargs echo" --split-by=timings #Get the list of tests for this container/VM
                    [ -s tmp/tests.txt ] || circleci-agent step halt #if there are no tests, terminate execution after this step
            - node/install-packages:
                pkg-manager: yarn      
            - run: mkdir ~/junit
            - run:
                name: Test application
                command: |
                    TEST_FILES=$(circleci tests glob "src/__tests__/*.js")
                    echo "$TEST_FILES" > glob-output.txt
                    echo "$TEST_FILES" | circleci tests run --command="xargs yarn test" --verbose --split-by=timings
            - run:
                command: cp junit.xml ~/junit/
                when: always
            - store_test_results:
                path: ~/junit
            - store_artifacts:
                path: ~/junit
            - store_artifacts:
                path: glob-output.txt

workflows:
    build-and-test:
      jobs:
        - build-and-test